backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pagina's"
    files:
      - name: "home"
        label: "Homepage"
        file: "content/home.json"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Tekst", name: "intro", widget: "text" }
